### ISSUE TITLE
Python3 support ?

### ISSUE THREAD

**Issue by asmodehn** [operatorequals/httpimport#10]
I couldn't help but notice that covertutils is python2 only, is it the same for httpimport ?
Any plan for python3 ?

I am also interested in similar topics, doing distributed software development in python, and I maintain a python 2/3 compatibility package for custom importers, in case it helps : https://github.com/asmodehn/filefinder2

**Comment by operatorequals** [comment]
Python3 is totally supported ;)

**Comment by asmodehn** [comment]
Good then :-) I just noticed the classifier in `setup.py`
