### ISSUE TITLE
Deprecation of imp.new_module

### ISSUE THREAD

**Issue by d53dave** [operatorequals/httpimport#13]
Since Python 3.4, many methods of the imp package, including `imp.new_module`, are [deprecated](https://bugs.python.org/issue17907).

I've been using `imp.new_module` myself in a side-project and I was curious if you had solved this problem. `new_module` is still working, but as it's an implementation detail, it might or might not disappear.

**Comment by operatorequals** [comment]
Solved as of `0.6.0` with [superloach's code](https://github.com/operatorequals/httpimport/pull/14)
