### ISSUE TITLE
How to disable own httpimport logging? (or raise its level)

### ISSUE THREAD

**Issue by wsw70** [operatorequals/httpimport#15]
My first use case for `httpimport` was a logging library common to several scripts:

```
# toconsole.py

import logging
import os

log = logging.getLogger(__name__)
log.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s %(message)s')
handler_console = logging.StreamHandler()
level = logging.DEBUG if 'DEV' in os.environ else logging.INFO
handler_console.setLevel(level)
handler_console.setFormatter(formatter)
log.addHandler(handler_console)

# disable httpimport logging except for errors+
logging.getLogger('httpimport').setLevel(logging.ERROR)
```

A simple usage such as

```
import httpimport

httpimport.INSECURE = True
with httpimport.remote_repo(['githublogging'], 'http://localhost:8000/') :
    from toconsole import log

log.info('yay!')
```

gives the following output

```
[!] Using non HTTPS URLs ('http://localhost:8000//') can be a security hazard!
2019-08-25 13:56:48,671 yay!
yay!
```

The second (bare) `yay!` must be coming from `httpimport`, namely from its logging setup.

How can I disable `httpimport` logging, or better - raise its level so that only errors+ are logged? The `logging.getLogger('httpimport').setLevel(logging.ERROR)` I tried did not work.

**Comment by operatorequals** [comment]
Well, you caught on me on that. To be fair I don't know why the `httpimport` logger is triggered from your module.
Yet, there is a somewhat un-elegant solution to that found [here](https://covertutils.readthedocs.io/en/latest/staging_exec.html) and it is as follows:
```bash
curl https://raw.githubusercontent.com/operatorequals/httpimport/master/httpimport.py | sed 's#log.*#pass#g' | grep -v "import pass" > httpimport_min.py
```

The `httpimport_min.py` file should contain the `httpimport` module without logging at all.

If you find a better way to achieve your objective respond here or/and submit a PR!

**Comment by operatorequals** [comment]
Can you post a reproducable code sample?
I'm back to work with this project so I could try and fix it

**Comment by operatorequals** [comment]
As also answered here:
https://stackoverflow.com/questions/57854037/how-to-silence-the-logging-of-a-module/58040797#58040797

It's fixed and waiting to be released.

**Comment by wsw70** [comment]
Thanks!

**Comment by operatorequals** [comment]
Now `0.7.2` (that contains the fix) is on PyPI:

https://pypi.org/project/httpimport/0.7.2/
