### ISSUE TITLE
"pip_load" function and PyPI support

### ISSUE THREAD

**Issue by operatorequals** [operatorequals/httpimport#17]
Given that the module will gain support for `tar.*` files (Issue #16), a function can be implemented that directly fetches tarballs from *pypi.org*, visiting the imported module's page, such as [https://pypi.org/project/<module>/#files](https://pypi.org/project/<module>/#files).
This page contains download links for all versions of `module`, that are not statically constructed. These links can be followed to download the tarball and later import it.

So a function `pip_load` can have the below signature:

```python
def pip_load(module, version="latest"):
[...]

```
----

Additionally, a context can be created, named `pip()` or `pip_repo`, directly importing to memory from PyPI, with the below usage:

```python
with pip():
  import module_in_pip
```

Finally, a function can be created that can parse `requirements.txt` files and directly load the dependencies using calls to `pip_load` or translating to `pip()` context commands.

**Comment by operatorequals** [comment]
To load contents of tarballs from PyPI a path truncating function has to be made.
A downloaded tarball looks as following:
```bash
wget https://files.pythonhosted.org/packages/c8/38/975ad2241b6912b9205d18a05150d4b24432d30e4f8d39ca727eb4506a46/covertutils-0.3.4.tar.gz
[...]
2019-09-13 14:52:25 (329 KB/s) - ‘covertutils-0.3.4.tar.gz’ saved [43968/43968]

unused@hostname:/tmp$ tar --list -f covertutils-0.3.4.tar.gz 
covertutils-0.3.4/
covertutils-0.3.4/covertutils/
covertutils-0.3.4/covertutils/datamanipulation/
covertutils-0.3.4/covertutils/datamanipulation/chunker.py
covertutils-0.3.4/covertutils/datamanipulation/compressor.py
```
Meaning that the package contents are not directly accessible in the tarball, but are inside another folder.

The aforementioned function must strip this first directory and make the package/module data directly accessible from the `loader` internals.

**Comment by operatorequals** [comment]
For the `requirements.txt` parsing idea, the native `pip` parser can be used as located [here](https://github.com/pypa/pip/blob/d23ecf0be2f013742380e97bfb87f062708ce8e0/src/pip/_internal/req/req_file.py)  `pip._internal.req.req_file`.

example:
```bash
$ cat requirements.txt 
httpimport==0.6.0
```
```python
>>> from pip._internal.req.req_file import parse_requirements
>>> for i in parse_requirements('requirements.txt', session=True): # 'session' has to be set to something
...     print(i)
... 
httpimport==0.6.0 (from -r requirements.txt (line 1))
>>> i.name
'httpimport'
```

**Comment by operatorequals** [comment]
it is notable that there is an official article about importing modules/packages from existent Python Wheels, and it is generally discouraged:
https://www.python.org/dev/peps/pep-0427/#is-it-possible-to-import-python-code-directly-from-a-wheel-file

**Comment by Aiyush-G** [comment]
Hi, could you give an example of how to use this with slightly more detail. Ie. PySide2 https://pypi.org/project/PySide2/ 

Thanks very much 
I look forward to your response :)

**Comment by operatorequals** [comment]
Looks like the package is not served in a repo and is not Python native. I'm afraid `httpimport` is not gonna work :(
