### ISSUE TITLE
Authenticated Requests to Github, GitLab, BitBucket

### ISSUE THREAD

**Issue by operatorequals** [operatorequals/httpimport#27]
As of now, `httpimport` works for only public repositories.

For developers in companies, enterprise environments, and generally people that work in private repositories a method is needed to remotely load packages/modules from private repos.

So this ticket addresses the integration of such methods (as per design and implementation) into the `[github|gitlab|bitbucket]_repo` methods:

--- 

* [x] GitHub
  * [ ] Design
  * [ ] Implementation

* [ ] BitBucket
  * [ ] Design
  * [ ] Implementation

* [ ] GitLab
  * [ ] Design
  * [ ] Implementation

The ticket will be updated for Design decisions and for accepted implementations for each of the platforms, with mentions to answers and commits.

**Comment by fgalan** [comment]
It would be great to implement this feature (at least for GitHub repositories)! :)

**Comment by operatorequals** [comment]
Looks like the solutions lies here:
https://stackoverflow.com/a/60198767/12099582

For Github, a Personal Token needs to be set as `Authorization` Header.
Specifically, the below `curl` to a Private Repo should work:

```bash
$ curl -H 'Authorization: token <Personal Token>' \
  https://raw.githubusercontent.com/<username>/<repo>/<branch>/<filepath>
```
You can create such token here: https://github.com/settings/tokens/new 
The only capabilities that the token needs is the `repo` one.

Now it has to get integrated to the module!

**Comment by operatorequals** [comment]
With version `v1.0.0` the [_Profiles_](https://github.com/operatorequals/httpimport#profiles) are now supported, that make it possible to set custom HTTP headers in a per-URL basis, enabling authentication to third-parties and more.

As now all header based authentication is implemented, this issue can finally get closed.
