### ISSUE TITLE
What does modules parameter is used for?

### ISSUE THREAD

**Issue by zqbake** [operatorequals/httpimport#32]
https://github.com/operatorequals/httpimport/blob/47786966477c03b12298fd6f23fd8ce9d23b9140/httpimport.py#L88

For my case, the codes below also work though I didn't specify modules

```python
import httpimport
url = "https://gist.githubusercontent.com/zhqu1148980644/435304b90d1511099b070414c760e968/raw/e388a5ba1e3580eb9f4cb9e3061ab1f47210cf94"
with httpimport.remote_repo([], url):
       import task
task.task1("asdasd")
```

**Comment by operatorequals** [comment]
It is an old idea that should be deprecated.
Yet, deprecating it will make the module not backward compatible.

You are right though!

**Comment by zqbake** [comment]
And also, if I change the link to link + task.py, the import would fail. What's the difference, they refer to the same content.

[link](https://gist.githubusercontent.com/zhqu1148980644/435304b90d1511099b070414c760e968/raw/6ebff9dd1767b520ab89cc3f6b8f8402f2523619/task.py)

**Comment by operatorequals** [comment]
This happens as `task.py` is the module filename.
The filenames are automatically searched from the URL. Appending the specific module as a file won't work.

**Comment by operatorequals** [comment]
This issue can be closed
