### ISSUE TITLE
Old module is imported when online file is changed

### ISSUE THREAD

**Issue by Mister-SOSA** [operatorequals/httpimport#36]
It seems as though the package is imported once, and continues to import from temp files without fetching the newest version from github.

**Comment by operatorequals** [comment]
Can you explain your problem further?

**Comment by Mister-SOSA** [comment]
Apologies, I forgot I had this issue open. The problem has since been relatively negligible, so I'll close the issue. I will, however, elaborate for people who may run into the same hiccup as I did.

My use case for this library was to have my python module hosted on the web, and my client side program would fetch the module on startup. This was great because I could just push changes to the script whenever I felt like it, and users would get the latest fixes and whatnot. This works fantastic for periodic updates, but my confusion came about during testing, when I was commiting multiple updates quickly. Upon launching the client side program, the newest version of the module would be imported and used just fine. For every launch thereafter, the program would just grab that downloaded module from the local temp directory instead of the web hosted version.

So what's going on?
It appears the imported module is stored locally for some amount of time before it's thrown away and refetched. This period of time was seemingly random, spanning anywhere from a couple minutes to an hour. At some point, those temp files would just be thrown away and refetched on the next launch. 

The solution:
Simply allow ample time from the point of commit to the expected time you'd want the client side application to receive the newest module, and it's all good. Eventually, all the temp files will be discarded and the client application will import the newest version of the module.
