### ISSUE TITLE
I encountered the following error when using the prompt

### ISSUE THREAD

**Issue by JmeterChen** [operatorequals/httpimport#37]
![image](https://user-images.githubusercontent.com/34080816/148735470-3967af9f-e8a6-4fec-98c6-67aaddfb6135.png)
![image](https://user-images.githubusercontent.com/34080816/148735508-75870da1-946b-440c-a6a0-e2a1e1937321.png)

**Comment by operatorequals** [comment]
Looks like your error is about modules that do not exist
