### ISSUE TITLE
Support packages with shared object files

### ISSUE THREAD

**Issue by rkbennett** [operatorequals/httpimport#38]
Not sure if this is something that's feasible, but there are multiple packages that required .so files to work, such as psutil. Is there a possibility of supporting packages like that? I understand there are implications with matching architecture and what not, but unless I'm missing something (entirely possible), there's no way to import a package like that currently.

**Comment by operatorequals** [comment]
You are correct! There are various reasons for that! The first is that the module only fetchs `.py` and `.pyc` files from HTTP/S URLs, so it won't even fetch `.so` or `.pyd` (Cython compiled) files.
Also, the only way that the module "knows" that something is added in the namespace is by using `exec`. And this works only with Python code (not native binaries).

Would be too neat to have such a feature though!

**Comment by operatorequals** [comment]
As this issue is not directly actionable, I am tagging it as `question` and archiving it.
