### ISSUE TITLE
Problem in Google Colab

### ISSUE THREAD

**Issue by ricardofrantz** [operatorequals/httpimport#45]
Hi, I am trying to import from gist in a google collab:
```
import httpimport
url = "https://gist.githubusercontent.com/ricardofrantz/96ee9d9fc253c2af30b0b9d6405f35ef/raw/2de95ca2d5b7b51aa2a3cfc6f248bc46eb9980d7"
with httpimport.remote_repo(url):
    import diff_matrix as df
L = df.diff_matrix()
print(L)
```
it seems there is some blockage in the ambient... is there a known way to bypass it?

> 
> WARNING:httpimport:[!] Using non HTTPS URLs ('http://localhost:8000//') can be a security hazard!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> DEBUG:httpimport:[!] Searching diff_matrix
> DEBUG:httpimport:[!] Path is None
> INFO:httpimport:[@] Checking if in declared remote module names >
> INFO:httpimport:[-] Not found!
> DEBUG:httpimport:FINDER=================
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> [<ipython-input-58-a76b92911295>](https://localhost:8080/#) in <module>
>       2 url = "https://gist.githubusercontent.com/ricardofrantz/96ee9d9fc253c2af30b0b9d6405f35ef/raw/2de95ca2d5b7b51aa2a3cfc6f248bc46eb9980d7"
>       3 with httpimport.remote_repo(url):
> ----> 4     import diff_matrix as df
>       5 L = df.diff_matrix()
>       6 print(L)
> 
> ModuleNotFoundError: No module named 'diff_matrix'
> 
> ---------------------------------------------------------------------------
> NOTE: If your import is failing due to a missing package, you can
> manually install dependencies using either !pip or !apt.
> 
> To view examples of installing some common dependencies, click the
> "Open Examples" button below.
> ---------------------------------------------------------------------------
> 

Thanks for your help,
Ricardo

**Comment by operatorequals** [comment]
Hello!
I think you need to update to 1.0.0 or newer. This syntax (of only passing a URL in 'remote_repo') is not available for older versions.

What is your httpimport version?

**Comment by ricardofrantz** [comment]
Hi, I tried updating to the latest version 1.1.0 in Google Collab and still have the error, but still outside Google Colab it works fine...

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: httpimport in /usr/local/lib/python3.9/site-packages (1.1.0)
Python 3.9.1
WARNING:httpimport:[!] Using non HTTPS URLs ('http://localhost:8000//') can be a security hazard!
DEBUG:httpimport:FINDER=================
DEBUG:httpimport:[!] Searching diff_matrix
DEBUG:httpimport:[!] Path is None
INFO:httpimport:[@] Checking if in declared remote module names >
INFO:httpimport:[-] Not found!
DEBUG:httpimport:FINDER=================
DEBUG:httpimport:[!] Searching diff_matrix
DEBUG:httpimport:[!] Path is None
INFO:httpimport:[@] Checking if in declared remote module names >
INFO:httpimport:[-] Not found!
DEBUG:httpimport:FINDER=================
DEBUG:httpimport:[!] Searching diff_matrix
DEBUG:httpimport:[!] Path is None
INFO:httpimport:[@] Checking if in declared remote module names >
INFO:httpimport:[-] Not found!
DEBUG:httpimport:FINDER=================
DEBUG:httpimport:[!] Searching diff_matrix
DEBUG:httpimport:[!] Path is None
INFO:httpimport:[@] Checking if in declared remote module names >
INFO:httpimport:[@] Checking if built-in >
INFO:httpimport:[@] Checking if it is name repetition >
INFO:httpimport:[*]Module/Package 'diff_matrix' can be loaded!
DEBUG:httpimport:LOADER=================
DEBUG:httpimport:[+] Loading diff_matrix
DEBUG:httpimport:[+] Trying to import as package from: 'http://localhost:8000//diff_matrix/__init__.py'
INFO:httpimport:[-] 'diff_matrix' is not a package:
DEBUG:httpimport:[+] Trying to import as module from: 'http://localhost:8000//diff_matrix.py'
INFO:httpimport:[-] 'diff_matrix' is not a module:
WARNING:httpimport:[!] 'diff_matrix' not found in HTTP repository. Moving to next Finder.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-87-5acccd7888cb>](https://localhost:8080/#) in <module>
     11 url = "https://gist.githubusercontent.com/ricardofrantz/96ee9d9fc253c2af30b0b9d6405f35ef/raw/32a239c770c123cb3bfc98d1287a612ded4b4eb5"
     12 with httpimport.remote_repo(url):
---> 13     import diff_matrix as df
     14 # L = df.diff_matrix()
     15 # print(L)

3 frames
/usr/lib/python3.8/importlib/_bootstrap.py in _load_backward_compatible(spec)

KeyError: 'diff_matrix'
```

**Comment by operatorequals** [comment]
I see. This is kind of weird.
I'll look into it.

To work around it you can try `remote_repo([], url)`, as it is the old syntax.

**Comment by operatorequals** [comment]
Looks like you still have an older version loaded. The current version (`1.1.0`) does not contain such log messages at all!
```bash
$ grep 'FINDER=================' httpimport.py
$ grep __version__ httpimport.py
__version__ = '1.1.0'
""".format(version=__version__, homepage=__github__)
```

Try:
```python
>>> import httpimport
>>> httpimport.__version__
???
```
to solve the mystery.

**Comment by operatorequals** [comment]
I'm closing this issue for now. If your problem is not solved feel free to re-open it!
