### ISSUE TITLE
attribute error module 'passman' has no attribute 'list_profiles'

### ISSUE THREAD

**Issue by zoudawen** [operatorequals/httpimport#48]
I am unable to determine whether the library in my gitlab repo is getting picked up; Its not throwing any errors. But when I try to access the function in from the imported module its saying that attribute does not exist. Any way for me to access the httpimporter class variables to check whats going on?

> Test.py

```
import httpimport
with httpimport.remote_repo("https://gitlab.mycompany.com/dz/co_library/"):
    import passman

print(dir(passman))
print(passman.__url__)
print(passman.list_profiles())
```

when I run the script to test it, im not seeing any of the function inside of passman.py and I get the following error:

```
['__builtins__', '__doc__', '__file__', '__loader__', '__package__', '__path__', '__spec__', '__url__']
https://gitlab.mycompany.com/dz/co_library/passman.py
Traceback (most recent call last):
   File "Test.py", line 6, in <module>
     print(passman.list_profiles()
AttributeError: module 'passman' has no attribute 'list_profiles'
```

> __init__.py from co_library

```
from . import *
```

> setup.py from co_library
```
from setuptools import setup, find_packages

setup(name="co_library", 
    version="0.1.0",
    packages=["passman",],
    py_modules=["passman",],
    )
```

**Comment by operatorequals** [comment]
Hello @zoudawen 🙃
What you want to do is not doable with the `httpimport.remote_repo` function. You need to check out the `gitlab_repo` function.

Additionally, if the repository is private, you'll need authentication, which you can do by setting `headers` in a `Named Profile` and using it with `gitlab_repo`.

Check the `README.md` for details (there is a similar example for Github)!

**Comment by zoudawen** [comment]
thanks, missing proxy information in my profile ini
