### ISSUE TITLE
How do I import from private github repo?

### ISSUE THREAD

**Issue by hermandr** [operatorequals/httpimport#51]
This is great! 
Thank you for your work.

I have a private repo that I would like to import from.
How do I do that?

**Comment by operatorequals** [comment]
Thanks a lot @hermandr 🙃
There are instructions specifically on that in the Readme:
https://github.com/operatorequals/httpimport#named-profiles

**Comment by hermandr** [comment]
John,

Thank you for the pointer to the readme.

When a github repo is private, it simply is not found in the http url when
accessed outside of the organisation/owner account.

I screenshot the readme section but does not contain instructions to access
a private github repo.  Is there further documentation on accessing a
private repo in github with an auth?

![image](https://user-images.githubusercontent.com/10177608/231920349-01f6cb4c-9b56-4d25-99fb-1bad6d35cf2a.jpeg)

**Comment by janalysis** [comment]
This works for me. There is just a delay. See https://github.com/operatorequals/httpimport/issues/52#issuecomment-2052540781

**Comment by operatorequals** [comment]
I'm closing this Issue as t seems resolved using Profiles.
