### ISSUE TITLE
AttributeError - unlcear how to import a Class from a module

### ISSUE THREAD

**Issue by cforce** [operatorequals/httpimport#53]
unable to get followig imported https://github.com/rosomri/atlassian-python-api imported via 
---
with httpimport.github_repo('rosomri', 'atlassian-python-api', ref='confluence_bugfix_export_pdf'):
    import atlassian
---
Traceback (most recent call last):
  File "C:\develop\git\scripts\collectors\confluence.py", line 213, in <module>
    confluence = connect_to_confluence(args.cf_url, args.cf_user, args.cf_token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\git\scripts\collectors\confluence.py", line 48, in connect_to_confluence
    return atlassian.Confluence(
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'atlassian' has no attribute 'Confluence'

What i am doing wrong?

**Comment by operatorequals** [comment]
Hey @cforce 🙃
I really don't see what this happens in first glance.
Can you provide the version of the module you are using?

**Comment by cforce** [comment]
i am using the latest of everything

**Comment by rkbennett** [comment]
Sorry for being late to the party, but after looking through the code and what the results are of importing that repo (at least for me), it appears there was a bug introduced to the submodule logic when the refactor happened. Specifically the else statement was removed from this conditional https://github.com/operatorequals/httpimport/blob/master/httpimport.py#L439 
This causes it to assume the `__package__` attribute to be the full module name, which breaks relative imports on submodules which are 2nd level submodules (i.e. package.module). The else statement needs to be added back which sets the __package__ attribute like this `mod.__package__ = name.split('.')[0]` though with the new code it would be pkg_name.

**Comment by cforce** [comment]
@rkbennett Would you provide a pull request with the fix, that would be great.

**Comment by operatorequals** [comment]
I'm here to review and merge a PR (and cut a release), but it would take a bit more for me to develop the fix, as I currently am not into computers all that much!

Cheers @rkbennett for finding tje culprit, I didn't have the time and energy to debug.

**Comment by rkbennett** [comment]
Done
