### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by rkbennett** [operatorequals/httpimport#58]
Starting in python 3.12 the find_module has been removed in favor of find_spec. The load_module function has also been deprecated in favor of the create_module and exec_module functions respectively. In order for this project to continue working for the latest python, these functions will need added. I have implemented them in my remote import hook package I wrote from the ground up if you want some ideas as to how this could be implemented. My repo is at [od_import](https://github.com/rkbennett/od_import).

**Comment by operatorequals** [comment]
Awesome project @rkbennett 🙃

When I get the time I'll read through your code and maybe fetch some of it!

You can always submit a PR if you need httpimport to work on 3.12 sooner than that, and I'll create a release ASAP 😉

**Comment by RusselWebber** [comment]
Thanks for creating this powerful project. httpimport is great!
Any news on Py 3.12 support?

**Comment by operatorequals** [comment]
Hello all!

I'm afraid I'll need your help with that... I don't have much time to handle Python 3.12 support right now.

I believe that all parts are already there (and not much new code is needed), but they need to be connected in a different way to implement the two new methods needed in Python 3.12.

I'll be more than happy to review and test PRs, and even contribute to them 🙃

**Comment by operatorequals** [comment]
I'm happy to announce that Python3.12 support is ready in [`v1.4.0`](https://pypi.org/project/httpimport/1.4.0/) :)

I finally had the time to properly read the new import protocol with `find_spec`, `create_module` and `exec_module`.

Support now is tested between Python3.7 to Python3.12

**Comment by operatorequals** [comment]
I'm closing this now, if anything comes up, please do not hesitate to open a new Issue!

**Comment by boludoz** [comment]
I've been using it with 3.12 for about a year now.
