### ISSUE TITLE
I can't get it to work with several tar.gz. packages

### ISSUE THREAD

**Issue by SeanTConrad** [operatorequals/httpimport#62]
I apologize if this is a simple error on my side.

I'm loading and using httpimport with this code.
```
import httpimport

verinfast_oss_url = "https://storage.googleapis.com/staging.startupos-328814.appspot.com/packages/verinfast_oss-2024.5.8140149.tar.gz"


with httpimport.remote_repo(verinfast_oss_url):
     import verinfast
```

I also enabled debug logging for httpimport.

I get these errors:
```
INFO     httpimport:httpimport.py:210 [*] Attempting extraction of 'verinfast_oss/__init__.py' from archive...
DEBUG    httpimport:httpimport.py:395 [-] Extraction of 'verinfast_oss/__init__.py' from archive failed. Trying next filepath...
DEBUG    httpimport:httpimport.py:398 [-] "filename 'verinfast_oss/__init__.py' not found"
INFO     httpimport:httpimport.py:427 [-] Module 'verinfast_oss' has not been found as loadable. 
```
I added some logging to show the contents of the downloaded archive before the not found errors:
```
    for member in archive_obj.getmembers():
        print(member)
    print(archive_obj.name)
    if isinstance(archive_obj, tarfile.TarFile):
        return archive_obj.extractfile(filepath).read()
```
It shows that the archive does have the `__init__.p`y file, but it's in a versioned root directory:
`<TarInfo 'verinfast_oss-2024.5.8140149/verinfast_oss/__init__.py' at 0x7f219d2a2a40>`

So the application is looking for `verinfast_oss/__init__.py` but the file is at `verinfast_oss-2024.5.8140149/verinfast_oss/__init__.py`.

Do I have something configured incorrectly or is this a potential issue?

**Comment by operatorequals** [comment]
I feel I've never come across a versioned tar Python module. It is possible that the module cannot be used with them.

If versioned tar Python modules are documented somewhere, we can happily start a PR to support them 🙃

**Comment by rkbennett** [comment]
This is an sdist file, the easiest solution is to reconstruct the tar so that the module folder is in the top level (get rid of the versioned folder)

**Comment by operatorequals** [comment]
I'm closing this, as it seems solved.
In case further investigation is needed, please re-open!
